### PR TITLE
Self host sigmac config files

### PR DESCRIPTION
**Pull request by YamatoSecurity**
Self host sigmac config files as they are not updated any more in the legacy repository.
Closes https://github.com/Yamato-Security/hayabusa-rules/issues/380

### CODE REVIEW

**Comment by YamatoSecurity** [comment]
@fukusuket Could I ask you to edit `convert.py` to use the new `sysmon.yaml`, `windows-audit.yaml` and `windows-services.yaml` that I uploaded to the `tools/sigmac` folder in this PR?
I think this will fix the FP problem with `service: smbclient-connectivity` rules.

**Comment by YamatoSecurity** [comment]
@fukusuket Thanks so much! I checked the changed rules but it seems that the new config files are not being used as the `smbclient-connectivity` rule did not add the `Channel`. We also need to change `convert.py` to use the new `sysmon.yaml`, etc... config files instead of the old `sysmon.yml`, etc... files, right?
I tried changing the file extension to `.yaml` but now it is failing. Could you check this when you have time?

**Comment by fukusuket** [comment]
@YamatoSecurity 
I'm sorry! I didn't notice that the extension of self host config is `yaml`...

>I tried changing the file extension to .yaml but now it is failing. Could you check this when you have time?

I fixed `convert.py` to covert `yml` file(not `yaml` file), but `convert.py` is still failing following warnings...
```
[WARNING ] Conversion of "posh_pc_tamper_with_windows_defender.yml" failed.
command: ['python3', './tools/sigmac', '-t', 'hayabusa', '-c', './tools/config/generic/windows-services.yaml', '-c', './tools/config/generic/windows-services.yaml', '--defer-abort', './rules/windows/powershell/powershell_classic/posh_pc_tamper_with_windows_defender.yml']
The configurations were provided in the wrong order (order key check in config file)
```
I'll check above warnings.

**Comment by YamatoSecurity** [comment]
@fukusuket Sorry I forgot to mention I had to use the `.yaml` extension because hayabusa will treat `.yml` files as detection rules and would get parsing errors when scanning.
I think `'hayabusa', '-c', './tools/config/generic/windows-services.yaml', '-c', './tools/config/generic/windows-services.yaml'` needs to be `'hayabusa', '-c', './tools/config/generic/windows-audit.yaml', '-c', './tools/config/generic/windows-services.yaml'`

`windows-services.yaml` shouldn't be used twice. It needs to convert first with `windows-audit.yml` and then `windows-services.yaml` after that.

**Comment by fukusuket** [comment]
@YamatoSecurity  I fixed warnings! Could you check the fix at your convenience?

**Comment by YamatoSecurity** [comment]
@fukusuket I checked it. Everything looks great now. It is converting with the new config files now.
Thank you!!

**Pull request merged**
