### PR TITLE
update sysmon default details

### PR DESCRIPTION
**Pull request by YamatoSecurity**
closes https://github.com/Yamato-Security/hayabusa-rules/issues/402
Could you check this?

### CODE REVIEW

**Comment by hitenkoku** [comment]
I checked

`> hayabusa.exe csv-timeline -d ../hayabusa-sample-evtx -o test.csv`


- [x]  EID : 4688

```
...
"2020-07-10 04:07:25.659 +09:00","fs02.offsec.lan","Sec",4688,"info",1145216,"Proc Exec","Cmdline: ""C:\Windows\system32\wevtutil.exe"" cl RTWorkQueueTheading ¦ Proc: C:\Windows\System32\wevtutil.exe ¦ PID: 0xa04 ¦ User: admmig ¦ LID: 0x1caf291"
```

- ❓  EID: 1


Unknown "Rule" field?

```
...
"2019-02-16 19:02:21.934 +09:00","PC01.example.corp","Sysmon",1,"info",1940899,"Proc Exec","Cmdline: plink.exe 10.0.2.18 -P 80 -C -R 127.0.0.3:4444:127.0.0.2:3389 -l test -pw test ¦ Rule: ¦ Proc: C:\Users\IEUser\Desktop\plink.exe ¦ User: PC01\IEUser ¦ ParentCmdline: ""C:\Windows\system32\cmd.exe"" ¦ LID: 0x26656 ¦ LGUID: 365ABB72-D6AB-5C67-0000-002056660200 ¦ PID: 2312 ¦ PGUID: 365ABB72-DFAD-5C67-0000-0010E0811500 ¦ ParentPID: 3904 ¦ ParentPGUID: 365ABB72-D92A-5C67-0000-0010CB580900 ¦ Description: Command-line SSH, Telnet, and Rlogin client ¦ Product: PuTTY suite ¦ Company: Simon Tatham ¦ Hashes: SHA1=7806AD24F669CD8BB9EBE16F87E90173047F8EE4"
```

- ❓  EID: 3

Unknown "Rule" field?

```
"2019-04-30 05:59:15.575 +09:00","IEWIN7","Sysmon",3,"info",8047,"Net Conn","Rule: ¦ Initiated: false ¦ Proto: tcp ¦ SrcIP: 10.0.2.18 ¦ SrcPort: 445 ¦ SrcHost: IEWIN7 ¦ TgtIP: 10.0.2.17 ¦ TgtPort: 63025 ¦ TgtHost: NLLT106876 ¦ User: NT AUTHORITY\SYSTEM ¦ Proc: System ¦ PID: 4 ¦ PGUID: 365ABB72-D9C4-5CC7-0000-0010EA030000"
...
```

- [x] EID: 6

```
"2020-02-10 17:28:12.981 +09:00","MSEDGEWIN10","Sysmon",6,"info",18766,"Signed Driver Loaded","Path: C:\Windows\System32\drivers\VBoxDrv.sys ¦ Sig: innotek GmbH ¦ Signed: true ¦ SigStatus: Valid ¦ Rule: ¦ Hashes: SHA1=7C1B25518DEE1E30B5A6EAA1EA8E4A3780C24D0C,MD5=EAEA9CCB40C82AF8F3867CD0F4DD5E9D,SHA256=CF3A7D4285D65BF8688215407BCE1B51D7C6B22497F09021F0FCE31CBEB78986,IMPHASH=B262E8D078EDE007EBD0AA71B9152863"
...
```

- [x] EID: 7

```
"2020-02-10 19:08:25.164 +09:00","MSEDGEWIN10","Sysmon",7,"low",20014,"DLL Loaded (Sysmon Alert)","Image: C:\Windows\System32\dbgcore.dll ¦ Proc: C:\Windows\System32\lsass.exe ¦ Description: Windows Core Debugging Helpers ¦ Product: Microsoft® Windows® Operating System ¦ Company: Microsoft Corporation ¦ Signed: true ¦ Sig: Valid ¦ PID: 624 ¦ PGUID: 747F3D96-A042-5E41-0000-0010E4560000 ¦ Hash: SHA1=E3FA87C983008D4D2A5D31708415F88548FC7702,MD5=88E88D8C1C663769BDD722000A7EB5A7,SHA256=C84BECA73EA45D3C53D9C42CD6A37CC0CC07FF57D9CFEE113CDF70F640572AEF,IMPHASH=9D75F08EA29885182B136CE4FF854114 ¦ OrigFilename: DBGCORE.DLL"
...
```

**Review by hitenkoku — CHANGES_REQUESTED** [review]
@YamatoSecurity Thanks for your pull request.

I wondered no output in `Rule` field on EID 1 and 3. ( ref: https://github.com/Yamato-Security/hayabusa-rules/pull/403#issuecomment-1545642301 )

Could you please confirm that this is the intended condition?

**Review by fukusuket — COMMENTED** [review]
I tested following environment :)
- Windows11
- Sysmon v14.16

with following rule.
```
title: TEST
id: b3c779ba-f638-40a0-a593-ddd45e8b1dda
status: experimental
description: TEST
author: TEST
date: 2023/05/13
detection:
  selection:
    Channel: Microsoft-Windows-Sysmon/Operational
    EventID:
      - 1
      - 3
  condition: selection
falsepositives:
  - Unknown
level: medium
ruletype: Sigma
``` 

I confirmed that EID3 has RuleName filed as follows!
```
2023-05-13 01:41:53.868 +09:00 ‖ FUKUSUKEEDBE ‖ Sysmon ‖ 3 ‖ med ‖ 504 ‖ TEST ‖ Rule: Usermode ¦ Initiated: true ¦ Proto: tcp ¦ SrcIP: 10.211.55.17 ¦ SrcPort: 54506 ¦ SrcHost: FUKUSUKEEDBE.localdomain ¦ TgtIP: 104.208.16.89 ¦ TgtPort: 443 ¦ TgtHost: - ¦ User: FUKUSUKEEDBE\fukusuke ¦ Proc: C:\Users\fukusuke\AppData\Local\Programs\Microsoft VS Code\Code.exe ¦ PID: 10684 ¦ PGUID: BB19D983-699E-645E-CF04-000000000400
```
But I could not get event EID 1 with RuleName ... How do you get it?
If you can set it, it's LGTM!

**Comment by YamatoSecurity** [comment]
@hitenkoku Thanks for the comment!
The RuleName was being displayed always just to make management easier but I think it will cause confusion so I changed it so the Rule field is not displayed unless the field exists and is not empty. Please check again.

**Review by hitenkoku — APPROVED** [review]
thanks for your comment.
LGTM.

**Comment by YamatoSecurity** [comment]
@hitenkoku @fukusuket 
Thank you both for checking!

**Pull request merged**
