### PR TITLE
support powershellcore

### PR DESCRIPTION
**Pull request by YamatoSecurity**
added support for powershellcore

### CODE REVIEW

**Review by hitenkoku — APPROVED** [review]
LGTM

I don't see any abbreviation for the channel display name "PowerShellCore", is it ok as it is?

**Comment by YamatoSecurity** [comment]
@hitenkoku Thank you! I forgot about that. I just added an abbreviation.

**Review by fukusuket — APPROVED** [review]
Iconfirmed that the event of PowerShellCore can be detected. LGTM！🚀
```
"Timestamp","Computer","Channel","EventID","Level","RecordID","RuleTitle","Details"
"2022-10-29 23:41:34.625 +09:00","win","PwShCore/Op",4104,"med ",15,"Potentially Malicious PwSh","MessageNumber: 1 ¦ MessageTotal: 50 ¦ Path: C:\program files\windowsapps\microsoft.powershell_7.2.7.0_x64__8wekyb3d8bbwe\Modules\PowerShellGet\PSModule.psm1 ¦ ScriptBlockId: 6eddf93a-f4dd-4cf9-b9f7-392b43974d9a ¦ ScriptBlockText: Import-LocalizedData LocalizedData -filename PSGet.Resource.psd1 ###...
```

**Comment by hitenkoku** [comment]
Thank you for the fix!

Confirmed. I think it's all good.

**Pull request merged**
