### PR TITLE
feat: add field mapping check for `process_creation` rule 

### LINKED ISSUE #443: Incomplete field conversion in `process_creation` rules
**Describe the bug**
`process_creation` rules are automatically converted to `EventID: 4688 (Security)` and `EventID: 1 (Sysmon)` rules.
However, due to imperfect field conversion, rules are created that cannot be detected. 

Currently, `logsource_mapping.py` does only the following field conversions.
https://github.com/Yamato-Security/hayabusa-rules/blob/65703b21168dd11a99b5f0ce640f612cb5fd63c0/tools/sigmac/windows-audit.yaml#L43-L48

**Actual behavior**
Undetectable rules are created. 
For example, the rule below uses field `ParentCommandLine`,`IntegrityLevel` that does not exist in `EventID: 4688 (Security)`
https://github.com/Yamato-Security/hayabusa-rules/blob/65703b21168dd11a99b5f0ce640f612cb5fd63c0/sigma/builtin/process_creation/proc_creation_win_uac_bypass_cleanmgr.yml#L19-L28

**Expected behavior**
Undetectable rules are not created. 
- If there are fields that can be converted, convert the fields correctly
- If there are **no** fields that can be converted, don't create post-conversion rules

**Additional context**
[The field check script in the Sigma repository](https://github.com/SigmaHQ/sigma/blob/cda0fbff62ce7f818198701452f1e0820f257b62/documentation/tools/sigma-logsource-checker.py#L101-L109) lists the following fields:

```
Channel: Security, EventID: 4688
"SubjectUserSid", 
"SubjectUserName", 
"SubjectDomainName", 
"SubjectLogonId", 
"NewProcessId", 
"NewProcessName", 
"TokenElevationType", 
"ProcessId", 
"CommandLine", 
"TargetUserSid", 
"TargetUserName", 
"TargetDomainName", 
"TargetLogonId", 
"ParentProcessName", 
"MandatoryLabel"
```

```
Channel: Microsoft-Windows-Sysmon/Operational, EventID: 1
"RuleName",
"UtcTime",
"ProcessGuid", 
"ProcessId", 
"Image", 
"FileVersion", 
"Description", 
"Product", 
"Company", 
"OriginalFileName", 
"CommandLine", 
"CurrentDirectory", 
"User", 
"LogonGuid", 
"LogonId", 
"TerminalSessionId", 
"IntegrityLevel", 
"Hashes", 
"ParentProcessGuid", 
"ParentProcessId", 
"ParentImage", 
"ParentCommandLine", 
"ParentUser"
```

### PR DESCRIPTION
**Pull request by fukusuket**
## What Changed

- Fixed #443 
- Changed so that `non-existent fields are not output` to the post-conversion rule in the `process_creation` rule conversion.

#### `process_creation` field conversion
| Sysmon | Security | Value conversion |
| --- | --- | --- | 
| User | SubjectUserName | Domain\User -> User | 
| User | SubjectDomainName | Domain\User -> Domain | 
| LogonId | SubjectLogonId | - | 
| ProcessId | NewProcessId | 2468 -> 0x9a4 (to hex) | 
| ParentProcessId | ProcessId | 7772 -> 0x1e5c  (to hex) | 
| Image | NewProcessName | - | 
| ParentImage | ParentProcessName | - | 
| IntegrityLevel | MandatoryLabel | High -> S-1-16-12288 | 

#### Fields for which post conversion rules are not created
If the following fields are in the `AND condition`(or `all of the OR conditions`), do not create post-conversion rules
```
Company
CurrentDirectory
Description
FileVersion
Hashes
LogonGuid
OriginalFileName
ParentCommandLine
ParentProcessGuid
ParentUser
ProcessGuid
Product
RuleName
TerminalSessionId
UtcTime
```

### Test Environment 
- OS: macOS montery version 13.1
- Hard: MacBook Air(M1, 2020) , Memory 8GB, Core 8
- Python 3.11.1

I would appreciate it if you could review🙏

### CODE REVIEW

**Comment by fukusuket** [comment]
## Evidence
### Environment 
- OS: macOS montery version 13.1
- Hard: MacBook Air(M1, 2020) , Memory 8GB, Core 8
- Python 3.11.1

### Test1
- TODO

### Test2
- TODO

**Comment by fukusuket** [comment]
### Test2 (`OR` conversion logic)

**Comment by fukusuket** [comment]
### Test3 (`AND` conversion logic)

**Comment by fukusuket** [comment]
### Test4 (`inconvertible` field)
When `inconvertible` fields,
(e.g [proc_creation_win_lolbin_ie4uinit.yml](https://github.com/SigmaHQ/sigma/blob/c0332a9d96f6c7804fcc85dd706caed889446a62/rules/windows/process_creation/proc_creation_win_lolbin_ie4uinit.yml#L22))

rules are not converted as follows
```
fukusuke@fukusukenoMacBook-Air sigmac % python logsource_mapping.py -r /Users/fukusuke/Scripts/Python/sigma/rules/windows/process_creation/proc_creation_win_lolbin_ie4uinit.yml
...
[ERROR:logsource_mapping.py:262] This rule has incompatible field.{'process_creation': {'EventID': 4688, 'Channel': 'Security'}, 'lolbin': [{'NewProcessName|endswith': '\\ie4uinit.exe'}, {'OriginalFileName': 'IE4UINIT.EXE'}], 'filter_correct': {'CurrentDirectory': ['c:\\windows\\system32\\', 'c:\\windows\\sysWOW64\\']}, 'filter_missing': {'CurrentDirectory': None}, 'condition': 'lolbin and not 1 of filter_*'}. skip conversion.
```

**Comment by fukusuket** [comment]
### Test5 (`hayabusa` no parse error)
There is no parse error with This PR's rules.
```
fukusuke@fukusukenoMacBook-Air hayabusa-2.6.0-all-platforms % ./hayabusa-2.6.0-mac-arm csv-timeline -d ../hayabusa-sample-evtx --debug -C -q -o new.csv -r ../new_rule
Start time: 2023/07/01 20:28

Total event log files: 584
Total file size: 138.2 MB

Loading detections rules. Please wait.

Excluded rules: 30

Deprecated rules: 162 (4.70%) (Disabled)
Experimental rules: 1924 (55.87%)
Stable rules: 100 (2.90%)
Test rules: 1420 (41.23%)
Unsupported rules: 42 (1.22%) (Disabled)

Sigma rules: 3444
Total enabled detection rules: 3444

Output profile: standard

Scanning in progress. Please wait.
```

The comparison result of the number of detections with main is as follows.
| Ver | Sigma rules | Hits / Total | crit(total/uniq) | high(total/uniq) | med(total/uniq) | low(total/uniq) | info(total/uniq) |
| --- | ---  | --- | --- | --- | --- | --- | --- |
| main | 3569 | 5,632 / 48,262 | 52 / 21 | 5,333 / 265 | 1,160 /  178 | 706 / 59  | 28 / 4  |
| This PR | 3444 | 5,434 / 48,262 | 52 / 21  | 5,305 / 261 | 1,155 / 177 | 399 / 58 | 99 / 5 |

**Comment by fukusuket** [comment]
### Test6 (Reason for the difference in the number of detections from main)

**Review by hitenkoku — APPROVED** [review]
LGTM.

**Comment by YamatoSecurity** [comment]
@fukusuket Thanks so much for the PR!

One question:
What happens if we have the following rule?
```
detection:
    lolbin:
        - Image|endswith: '\ie4uinit.exe'
        - OriginalFileName: 'IE4UINIT.EXE'
    filter_correct:
        CurrentDirectory:
            - 'c:\windows\system32\'
            - 'c:\windows\sysWOW64\'
    filter_high:
        IntegrityLevel: High
    condition: lolbin and not 1 of filter_*
```

That is, one filter section with incompatible fields but another filter section with a compatible field.

Also, when it is `all of filter*`, the 4688 rule will not be created, right?
```
detection:
    lolbin:
        - Image|endswith: '\ie4uinit.exe'
        - OriginalFileName: 'IE4UINIT.EXE'
    filter_correct:
        CurrentDirectory:
            - 'c:\windows\system32\'
            - 'c:\windows\sysWOW64\'
    filter_high:
        IntegrityLevel: High
    condition: lolbin and not all of filter_*
```

because although it has a section with compatible fields (filter_high) it also relies on a section that includes incompatible fields (filter_correct).

**Comment by YamatoSecurity** [comment]
When a rule is filtering on a section with compatible fields OR a section with in-compatible fields then not creating a 4688 rule will lower FPs but may result in decrease of TPs... so I am wondering what the best way is.
What about converting rules in these cases but adding an extra label to mark that there is a higher chance of FPs?
For example, in such rules, we could add `incompleterule: true` to the end of the YML file.
Then in the next version of Hayabusa, we could add a `--no-incomplete-rules` option that will ignore all rules that are marked as `incompleterule: true`.
This will let us keep the detection rate the same as it is now but give the user the option of doing more accurate scans if they are getting too many FPs, etc...

What do you think?

(I don't want to lower the detection rate by default)

**Comment by fukusuket** [comment]
@YamatoSecurity 
Thank you so much for your review :) 

> That is, one filter section with incompatible fields but another filter section with a compatible field.

I see, I hadn't thought of [this case](https://github.com/Yamato-Security/hayabusa-rules/pull/445#issuecomment-1616160031)...😅 I agree with you, in this case it would be better to create a rule.
It seems a little difficult, but I will check if it can be implemented💪

At first, I'll count how many rules match this case and I'll understand the characteristics!

**Comment by fukusuket** [comment]
@YamatoSecurity 

Addressing `1 of *` or `all of * ` **completely** is a bit expensive(Because need a new implementation of condition block grammar parsing) to implement... :( 

Although it is not a perfect countermeasure, I tried the implementation below, what do you think? 🤔

### Number of `process_creation` rules

The result of checking the `process_creation` rule was as follows.
| No | description | count |
| --- | --- | ---:|
| 1 |`process_creation` rule total count | 1,326 |
| 2 |Has fields `unique to Sysmon` | 662 / 1,326 |
| 3 |Has fields `unique to Sysmon` and  condition with `all of */ 1 of *` | 484 / 1,326 |
| 4 |Has fields `unique to Sysmon` and  condition **without** `all of */ 1 of *` | 178 / 1,326 |
| 5 |Has fields `unique to Sysmon` and  condition **without** `all of */ 1 of *` and `undetectable rule`  |   61 / 1,326 |

### New Implementation
I changed the implementation(https://github.com/Yamato-Security/hayabusa-rules/pull/445/commits/460d7f11fa43bb9f97a83debdd6a9a4a4c46062c) to check only the case `No.5`. then result is as follows.

| Ver | Sigma rules | Hits / Total | crit(total/uniq) | high(total/uniq) | med(total/uniq) | low(total/uniq) | info(total/uniq) |
| --- | ---  | --- | --- | --- | --- | --- | --- |
| main | 3569 | 5,632 / 48,262 | 52 / 21 | 5,333 / 265 | 1,160 /  178 | 706 / 59  | 28 / 4  |
| https://github.com/Yamato-Security/hayabusa-rules/pull/445/commits/460d7f11fa43bb9f97a83debdd6a9a4a4c46062c | 3499 | 5,704 / 48,262 | 52 / 21  | 5,334 / 266 | 1,163 / 179 | 706 / 59 | 99 / 5 |

The diff is as follows.
(`old.csv` is `main` result / `fix.csv` is https://github.com/Yamato-Security/hayabusa-rules/pull/445/commits/460d7f11fa43bb9f97a83debdd6a9a4a4c46062c result )
```
hayabusa-2.6.0-all-platforms % cat old.csv | awk -F"," '{print $5, $7}' | sort | uniq -c > old-rule-count.csv
hayabusa-2.6.0-all-platforms % cat fix.csv | awk -F"," '{print $5, $7}' | sort | uniq -c > fix-rule-count.csv
hayabusa-2.6.0-all-platforms % diff old-rule-count.csv fix-rule-count.csv
220c220
<    1 "high" "Suspicious Spool Service Child Process"
---
>    2 "high" "Suspicious Spool Service Child Process"
251a252
>   71 "info" "Suspicious High IntegrityLevel Conhost Legacy Option"
369a371
>    3 "med" "Potential RDP Session Hijacking Activity"
```

Rules using `1 of *` or  `all of *` are often valid rules(such as https://github.com/Yamato-Security/hayabusa-rules/pull/445#issuecomment-1616160031), so it's not a perfect countermeasure, 
but for now, I think https://github.com/Yamato-Security/hayabusa-rules/pull/445/commits/460d7f11fa43bb9f97a83debdd6a9a4a4c46062c is better. Because with https://github.com/Yamato-Security/hayabusa-rules/pull/445/commits/460d7f11fa43bb9f97a83debdd6a9a4a4c46062c I can detect more with fewer rules.

**Review by YamatoSecurity — APPROVED** [review]
@fukusuket 
Thanks for looking into the different cases! LGTM!
Please merge this when ready. I updated the Changelog. Please check the Japanese version and fix if any mistakes.

**Comment by fukusuket** [comment]
@YamatoSecurity 
Thank you for checking and update changelog :)  
I updated the Japanese changelog a little because the number has changed. I would appreciate it if you could review🙏

**Comment by YamatoSecurity** [comment]
@fukusuket Thanks so much! I updated the count in the English changelog as well so I will merge this.

**Pull request merged**
