### PR TITLE
Added rules to detect ISO mounting

### PR DESCRIPTION
**Pull request by YamatoSecurity**
I added rules to detect ISO and VHD mounting.

### CODE REVIEW

**Review by hitenkoku — COMMENTED** [review]
@YamatoSecurity 
Thank you for your pull request.
It appears that %VhdFile% and %ReadOnly% are not registered in eventkey_alias.txt.

Am I correct in assuming that you have determined that this is not a problem since they are under EventData?

**Comment by YamatoSecurity** [comment]
@hitenkoku Thank you for checking!
Yes, since they are in the normal location I figured it would be fine to not define them.
Regarding speed, is there any difference? (Would defining them be better?)

**Comment by hitenkoku** [comment]
@YamatoSecurity Thank you for your comment.

I don't see any significant difference in terms of speed.

I'm at https://github.com/Yamato-Security/hayabusa/blob/82e132c0ef7765322e38e1a71e5c4df491ad0b8b/src/detections/message.rs#L201-L205. If the Alias doesn't match, it looks under Event.EventData.

**Review by fukusuket — APPROVED** [review]
I confirmed this rule detection on Windows 11 :) LGTM!🚀

```
C:\tmp\hayabusa-2.4.0-win-64-bit>hayabusa-2.4.0-win-x64.exe csv-timeline -l -r hayabusa-rules\hayabusa\builtin\VHDMP_Op -q
Start time: 2023/05/05 20:17

Total event log files: 348
Total file size: 92.7 MB

Loading detections rules. Please wait.


Experimental rules: 2 (66.67%)
Stable rules: 1 (33.33%)

Hayabusa rules: 3
Total enabled detection rules: 3

Scanning in progress. Please wait.

348 / 348 [==========================================================================================================================================================] 100.00 %

Timestamp ‖ Computer ‖ Channel ‖ EventID ‖ Level ‖ RecordID ‖ RuleTitle ‖ Details
2023-05-05 17:17:30.226 +09:00 ‖ FUKUSUKEEDBE ‖ MS-Win-VHDMP-Op ‖ 12 ‖ low  ‖ 29 ‖ ISO Mounted ‖ Path: \\?\C:\tmp\Win11_22H2_Japanese_x64v1.iso ¦ ReadOnly: false
2023-05-05 17:49:48.213 +09:00 ‖ FUKUSUKEEDBE ‖ MS-Win-VHDMP-Op ‖ 12 ‖ low  ‖ 42 ‖ VHDX Mounted ‖ Path: \\?\C:\windows.vhdx ¦ ReadOnly: false
2023-05-05 17:50:04.858 +09:00 ‖ FUKUSUKEEDBE ‖ MS-Win-VHDMP-Op ‖ 12 ‖ low  ‖ 72 ‖ VHDX Mounted ‖ Path: \\?\C:\windows.vhdx ¦ ReadOnly: false
2023-05-05 17:50:04.860 +09:00 ‖ FUKUSUKEEDBE ‖ MS-Win-VHDMP-Op ‖ 12 ‖ low  ‖ 88 ‖ VHDX Mounted ‖ Path: \\?\C:\windows.vhdx ¦ ReadOnly: false
2023-05-05 17:56:33.957 +09:00 ‖ FUKUSUKEEDBE ‖ MS-Win-VHDMP-Op ‖ 12 ‖ low  ‖ 111 ‖ VHDX Mounted ‖ Path: \\?\C:\windows2.vhdx ¦ ReadOnly: false
2023-05-05 17:56:41.820 +09:00 ‖ FUKUSUKEEDBE ‖ MS-Win-VHDMP-Op ‖ 12 ‖ low  ‖ 141 ‖ VHDX Mounted ‖ Path: \\?\C:\windows2.vhdx ¦ ReadOnly: false
2023-05-05 17:56:41.825 +09:00 ‖ FUKUSUKEEDBE ‖ MS-Win-VHDMP-Op ‖ 12 ‖ low  ‖ 157 ‖ VHDX Mounted ‖ Path: \\?\C:\windows2.vhdx ¦ ReadOnly: false

Rule Authors:

╭─────────────────╮
│ Zach Mathis (2) │
╰─────────────────╯

Results Summary:

First Timestamp: 2023-05-02 07:39:22.360 +09:00
Last Timestamp: 2023-05-05 20:16:46.893 +09:00

Events with hits / Total events: 7 / 49,136 (Data reduction: 49,129 events (99.99%))

Total | Unique detections: 7 | 2
Total | Unique critical detections: 0 (0.00%) | 0 (0.00%)
Total | Unique high detections: 0 (0.00%) | 0 (0.00%)
Total | Unique medium detections: 0 (0.00%) | 0 (0.00%)
Total | Unique low detections: 7 (100.00%) | 2 (100.00%)
Total | Unique informational detections: 0 (0.00%) | 0 (0.00%)

Dates with most total detections:
critical: n/a, high: n/a, medium: n/a, low: 2023-05-05 (7), informational: n/a

Top 5 computers with most unique detections:
critical: n/a
high: n/a
medium: n/a
low: FUKUSUKEEDBE (2)
informational: n/a

╭──────────────────────────────────────────────╮
│ Top critical alerts:        Top high alerts: │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ n/a                         n/a              │
│ n/a                         n/a              │
│ n/a                         n/a              │
│ n/a                         n/a              │
│ n/a                         n/a              │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ Top medium alerts:          Top low alerts:  │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ n/a                         VHDX Mounted (6) │
│ n/a                         ISO Mounted (1)  │
│ n/a                         n/a              │
│ n/a                         n/a              │
│ n/a                         n/a              │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ Top informational alerts:                    │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ n/a                         n/a              │
│ n/a                         n/a              │
│ n/a                         n/a              │
│ n/a                         n/a              │
│ n/a                         n/a              │
╰───────────────────────────╌──────────────────╯

Elapsed time: 00:00:01.475

```

**Comment by YamatoSecurity** [comment]
@hitenkoku Thanks! in that case, maybe I will keep the config file minimal to what needs to be custom defined.
@fukusuket Thank you for checking!

**Pull request merged**
