### PR TITLE
Add "NTFS volume mounted" rule

### PR DESCRIPTION
**Pull request by Qazeer**
Hello!

This PR adds a rule for the event 4 of the channel "Microsoft-Windows-Ntfs/Operational", that tracks mounting of NTFS volumes. Can be useful in correlation with the 'Device Conn' rule to retrieve the volume label / name associated with the device.

Attempt to filter events from normal system usage, but some noise is expected.

### CODE REVIEW

**Review by YamatoSecurity — CHANGES_REQUESTED** [review]
@Qazeer Thanks alot! This looks like a good rule. Just one thing, can you add `DeviceName` and `IsBootVolume` to the `details` field?

**Comment by Qazeer** [comment]
From my testing, it appears that the `DeviceName` field is set to the physical device path associated with the volume (such as `\Device\HarddiskVolume7`). It is the case on `Windows 10` / `11` (a few builds tested) and `Windows Server 2016` to `2022`.
May be adding the `DeviceSerialNumber` instead / as well for more details and correlation on the device would be better?

Regarding the `IsBootVolume`, I have added a filter to remove the boot volume (`IsBootVolume: true`) so it would always be set to false. Should I also remove that filter? It would be a trade-off between noise and exhaustivity.

I will implement the changes you deem best, and update the PR :)

**Comment by YamatoSecurity** [comment]
@Qazeer I see. Sorry I did not take a good look at the filter section. Yes, I think it would be better to filter out the boot partitions and and not include `IsBootVolume`.

**Review by YamatoSecurity — APPROVED** [review]
LGTM!

**Pull request merged**
