### PR TITLE
refactor: remove unused logsource-mapping.yaml

### PR DESCRIPTION
**Pull request by fukusuket**
## What Changed
Delete logsource-mapping.yaml as it is not currently referenced.
Currently, logsource-mapping is performed in the following files:
- https://github.com/Yamato-Security/sigma-to-hayabusa-converter/blob/main/builtin-category-mapping.yaml
- https://github.com/Yamato-Security/sigma-to-hayabusa-converter/blob/main/services-mapping.yaml
- https://github.com/Yamato-Security/sigma-to-hayabusa-converter/blob/main/sysmon-category-mapping.yaml

I would appreciate it if you could check it out when you have time🙏

### CODE REVIEW

**Comment by fukusuket** [comment]
### Test
As shown below, I confirmed that no errors occurred and that there were no differences in the CSV files.
```
% ./hayabusa-2.16.0-mac-aarch64 csv-timeline -d ../hayabusa-sample-evtx -w -q -C -D -n -u -o old.csv
% mv rules/config/logsource-mapping.yaml ../
% ./hayabusa-2.16.0-mac-aarch64 csv-timeline -d ../hayabusa-sample-evtx -w -q -C -D -n -u -o new.csv
% diff new.csv old.csv
%
```

**Comment by fukusuket** [comment]
The following rule parsing error is caused by the lack of a linux version in the 2.16.1 release binary and is not related to this PR fix.
- https://github.com/Yamato-Security/hayabusa-rules/actions/runs/10233142948/job/28311092207?pr=692#step:5:209

@YamatoSecurity 
Could you please make hayabusa-2.16.1-linux-intel.zip?🙏 (Due to this Actions error, the hayabusa_rule repository is currently not up-to-date.)

**Comment by fukusuket** [comment]
>@YamatoSecurity 
Could you please make hayabusa-2.16.1-linux-intel.zip?🙏 (Due to this Actions error, the hayabusa_rule repository is currently not up-to-date.)

I have temporarily fixed the reference to the 2.16.0 release binary; when 2.17.0 is released, I will change Actions back to refer to the latest release. Sorry, so the 2.16.1 linux binary is not needed!

**Review by YamatoSecurity — APPROVED** [review]
@fukusuket Ok, sorry for forgetting about the linux binary! Thank you!

**Pull request merged**
