### PR TITLE
readme-2.19.0

### PR DESCRIPTION
**Pull request by YamatoSecurity**
@fukusuket Could you check this over and could I ask you to do update the Japanese translations?

Also closes https://github.com/Yamato-Security/hayabusa-rules/issues/754

### CODE REVIEW

**Comment by YamatoSecurity** [comment]
@fukusuket I forgot to mention, could you also update `support-modifier.py` to support the new modifiers (`lt`, etc..)?

I noticed that `fieldref|startswith` and `fieldref|contains` are not listed in the supported field modifiers, so can you add these?

**Review by fukusuket — APPROVED** [review]
LGTM!!🚀 I updated Japanese README and supported-modifier.py!

**Comment by fukusuket** [comment]
>I noticed that fieldref|startswith and fieldref|contains are not listed in the supported field modifiers, so can you add these?

I updated!!💪

**Comment by YamatoSecurity** [comment]
Thanks so much for the update!
One more thing, could you also add the following to the supported modifiers: `startswith|cased`, `endswith|cased`, `contains|cased`

I think we should document because I forgot how `cased` gets used. 😄

**Comment by fukusuket** [comment]
Yes, I updated it!!💪

**Pull request merged**
