### PR TITLE
feat: Comments in yaml are left as is

### LINKED ISSUE #408: Comments are erased when converting rules
@fukusuket 
Sorry I just noticed that comments get erased when converted. Is it possible to copy over the comments from the original sigma rules? This would be make reading and understanding the sigma rules a bit easier without having to look up the original rule.

### PR DESCRIPTION
**Pull request by fukusuket**
## What Changed
- Fixed #408 

### Test Environment 
- OS: macOS Sonoma version 14.0
- Hard: MacBook Air(M1, 2020) , Memory 8GB, Core 8
- Poetry: version 1.7.1

### Test1
As shown below, comments remain even after conversion
```
title: Microsoft Malware Protection Engine Crash
id: 545a5da6-f103-4919-a519-e9aec1026ee4
related:
    - id: 6c82cf5c-090d-4d57-9188-533577631108
      type: similar
status: experimental
description: This rule detects a suspicious crash of the Microsoft Malware Protection Engine
references:
    - https://bugs.chromium.org/p/project-zero/issues/detail?id=1252&desc=5
    - https://technet.microsoft.com/en-us/library/security/4022344
author: Florian Roth (Nextron Systems)
date: 2017/05/09
modified: 2023/04/14
tags:
    - attack.defense_evasion
    - attack.t1211
    - attack.t1562.001
logsource:
    product: windows
    service: application
    # warning: The 'data' field used in the detection section is the container for the event data as a whole. You may have to adapt the rule for your backend accordingly
detection:
    application:
        Channel: Application
    selection:
        Provider_Name: Application Error
        EventID: 1000
        Data|contains|all:
            - MsMpEng.exe
            - mpengine.dll
    condition: application and selection
falsepositives:
    - MsMpEng might crash if the "C:\" partition is full
level: high
ruletype: Sigma
```

```
title: Mimikatz Use
id: 06d71506-7beb-4f22-8888-e2e5e2ca7fd8
status: test
description: This method detects mimikatz keywords in different Eventlogs (some of them only appear in older Mimikatz version that are however still used by different threat groups)
references:
    - https://tools.thehacker.recipes/mimikatz/modules
author: Florian Roth (Nextron Systems), David ANDRE (additional keywords)
date: 2017/01/10
modified: 2022/01/05
tags:
    - attack.s0002
    - attack.lateral_movement
    - attack.credential_access
    - car.2013-07-001
    - car.2019-04-004
    - attack.t1003.002
    - attack.t1003.004
    - attack.t1003.001
    - attack.t1003.006
logsource:
    product: windows
detection:
    keywords:
        - dpapi::masterkey
        - eo.oe.kiwi
        - event::clear
        - event::drop
        - gentilkiwi.com
        - kerberos::golden
        - kerberos::ptc
        - kerberos::ptt
        - kerberos::tgt
        - Kiwi Legit Printer
        - 'lsadump::'
        - mimidrv.sys
        - \mimilib.dll
        - misc::printnightmare
        - misc::shadowcopies
        - misc::skeleton
        - privilege::backup
        - privilege::debug
        - privilege::driver
        - 'sekurlsa::'
    filter:
        EventID: 15  # Sysmon's FileStream Events (could cause false positives when Sigma rules get copied on/to a system)
    condition: keywords and not filter
falsepositives:
    - Naughty administrators
    - AV Signature updates
    - Files with Mimikatz in their filename
level: high
ruletype: Sigma

```

### CODE REVIEW

**Comment by fukusuket** [comment]
### Test2
`logsource_mapping.py` completes normally as shown below
```
 % poetry run python logsource_mapping.py -r ../../../sigma -o ./converted_sigma_rules
[INFO:logsource_mapping.py:456] Start to logsource mapping sigma rules.
...
[INFO:logsource_mapping.py:514] [4149] files created successfully. Created files were saved under [./converted_sigma_rules].
[INFO:logsource_mapping.py:515] Script took [72.73] seconds.
```

**Comment by fukusuket** [comment]
### Test3
Parse error does not occur in rules after conversion.
```
% ./hayabusa-2.12.0-mac-aarch64 csv-timeline -d ../hayabusa-sample-evtx -w -D -n -u -q -o new.csv -C
Start time: 2024/01/22 22:59

Total event log files: 583
Total file size: 137.1 MB

Loading detection rules. Please wait.

Excluded rules: 26
Noisy rules: 12

Deprecated rules: 195 (4.54%)
Experimental rules: 1145 (26.65%)
Stable rules: 251 (5.84%)
Test rules: 2660 (61.92%)
Unsupported rules: 45 (1.05%)

Hayabusa rules: 173
Sigma rules: 4123
Total enabled detection rules: 4296

Output profile: standard

Scanning in progress. Please wait.

[00:00:07] 583 / 583   [========================================] 100%

Scanning finished. Please wait while the results are being saved.

Rule Authors:

╭────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Florian Roth (201)                oscd.community (122)               Zach Mathis (119)                 Nasreddine Bencherchali (111)   │
│ frack113 (104)                    Tim Shelton (36)                   Daniil Yugoslavskiy (26)          Teymur Kheirkhabarov (25)       │
│ Jonhnathan Ribeiro (23)           Thomas Patzke (21)                 Tim Rauch (18)                    Timur Zinniatullin (17)         │
│ Christian Burkard (17)            Roberto Rodriguez @Cyb3r... (15)   Markus Neis (15)                  Roberto Rodriguez (14)          │
│ E.M. Anhaus (14)                  Michael Haag (12)                  Samir Bousseaden (11)             Endgame) (9)                    │
│ OTR (9)                           Swachchhanda Shrawan Poudel (9)    Victor Sergeev (9)                Natalia Shornikova (8)          │
│ David ANDRE (8)                   juju4 (8)                          Endgame (7)                       JHasenbusch (7)                 │
│ Ecco (6)                          X__Junior (6)                      Sander Wiebing (5)                omkar72 (5)                     │
│ Gleb Sukhodolskiy (5)             Ilyas Ochkov (4)                   Janantha Marasinghe (4)           Max Altgelt (4)                 │
│ Tobias Michalski (4)              Eric Conrad (4)                    Christopher Peacock @sec... (4)   @neu5ron (4)                    │
│ keepwatch (4)                     Mauricio Velazco (4)               Arnim Rupp (4)                    elhoim (3)                      │
│ Sherif Eldeeb (3)                 Yusuke Matsui (3)                  SCYTHE @scythe_io (3)             FPT.EagleEye Team (3)           │
│ Elastic (3)                       SOC Prime (3)                      Aleksey Potapov (3)               Alexandr Yampolskyi (3)         │
│ Andreas Hunkeler (3)              @twjackomo (3)                     Cyb3rEng (3)                      Tom Ueltschi (3)                │
│ Nikita Nazarov (3)                Austin Songer @austinsonger (3)    Wojciech Lesicki (3)              Daniel Bohannon (3)             │
│ James Pemberton@4A616D6573 (3)    Jakob Weinzettl (3)                Perez Diego (3)                   Harish Segar (3)                │
│ Hieu Tran (3)                     Fukusuke Takahashi (3)             pH-T (3)                          FPT.EagleEye (3)                │
│ wagga (3)                         Vasiliy Burov (3)                  Vadim Khrykov (3)                 Dimitrios Slamaris (3)          │
│ Mark Russinovich (3)              Maxime Thiebaut (2)                Karneades (2)                     Hosni Mribah (2)                │
│ Tony Lambert (2)                  Oleg Kolesnikov @securon... (2)    Sreeman (2)                       Relativity (2)                  │
│ Yassine Oukessou (2)              Chakib Gzenayi (2)                 Mark Woan (2)                     Tony Lambert) (2)               │
│ D3F7A5105 (2)                     Romaissa Adjailia (2)              Margaritis Dimitrios (2)          Justin C. (2)                   │
│ James Dickenson (2)               Bartlomiej Czyz (2)                Nik Seetharaman (2)               Anton Kutepov (2)               │
│ Modexp (2)                        Trent Liffick (2)                  Sean Metcalf (2)                  @2xxeformyshirt (2)             │
│ @dreadphones (2)                  Zach Stanford @svch0st (2)         @SBousseaden (2)                  James Pemberton@4A616D65... (2) │
│ Maxim Pavlunin (1)                Tuan Le (1)                        Cedric MAURUGEON (1)              @scythe_io (1)                  │
│ @svch0st (1)                      David Strassegger (1)              NVISO (1)                         Semanur Guneysu @semanurtg (1)  │
│ blueteam0ps (1)                   Tom Kern (1)                       Mustafa Kaan Demir (1)            Zaw Min Htun (1)                │
│ Julia Fomina (1)                  @caliskanfurkan_ (1)               Fatih Sirin (1)                   Cédric Hien (1)                 │
│ Bartlomiej Czyz @bczyz1 (1)       Jason Lynch (1)                    Christopher Peacock @Sec... (1)   rukawa (1)                      │
│ Markus Neis @Karneades (1)        KevTheHermit (1)                   Mangatas Tondang (1)              Oddvar Moe (1)                  │
│ j4son (1)                         Dominik Schaudel (1)               fuzzyf10w (1)                     Tom U. @c_APT_ure (1)           │
│ Georg Lauenstein (1)              vburov (1)                         Kutepov Anton (1)                 Subhash Popuri (1)              │
│ Stamatis Chatzimangou (1)         @gott_cyber (1)                    Sorina Ionescu (1)                Pushkarev Dmitry (1)            │
│ @oscd_initiative (1)              @Joseliyo_Jstnk (1)                Joshua Wright (1)                 SBousseaden (1)                 │
│ James Pemberton @4A616D6573 (1)   Aaron Herman (1)                   Jose Rodriguez (1)                SCYTHE (1)                      │
│ David Burkett (1)                 @atc_project (1)                   @signalblur (1)                   Dave Kennedy (1)                │
│ Sami Ruohonen (1)                 Austin Songer (1)                  Swisscom CSIRT (1)                CD_ROM_ (1)                     │
│ Matthew Green @mgreen27 (1)       Andreas Braathen (1)               Anish Bogati (1)                  @juju4 (1)                      │
│ EagleEye Team (1)                 Jeff Warren (1)                    Center for Threat Inform... (1)   Dan Beavin) (1)                 │
│ Ivan Dyachkov (1)                 Alec Costello (1)                  Dmitriy Lifanov (1)               John Lambert (1)                │
│ Teymur Kheirkhabarov @He... (1)   Omer Faruk Celik (1)               Open Threat Research (1)          mdecrevoisier (1)               │
│ Scott Dermott (1)                 Furkan CALISKAN (1)                Timon Hackenjos (1)               Jai Minton (1)                  │
│ alias support) (1)                Maxence Fossat (1)                 Joseliyo Sanchez (1)              Bhabesh Raj (1)                 │
│ Benjamin Delpy (1)                Jack Croock (1)                                                                                      │
╰─────────────────────────────────╌──────────────────────────────────╌─────────────────────────────────╌─────────────────────────────────╯

Results Summary:

Events with hits / Total events: 20,993 / 47,465 (Data reduction: 26,472 events (55.77%))

Total | Unique detections: 34,755 | 650
Total | Unique critical detections: 54 (0.16%) | 20 (3.08%)
Total | Unique high detections: 6,064 (17.45%) | 256 (39.38%)
Total | Unique medium detections: 2,348 (6.76%) | 226 (34.77%)
Total | Unique low detections: 6,647 (19.13%) | 82 (12.62%)
Total | Unique informational detections: 19,642 (56.52%) | 66 (10.15%)

Dates with most total detections:
critical: 2019-07-19 (16), high: 2016-09-20 (3,649), medium: 2019-05-19 (250), low: 2016-09-20 (3,723), informational: 2016-08-19 (2,129)

Top 5 computers with most unique detections:
critical: MSEDGEWIN10 (10), FS03.offsec.lan (2), IEWIN7 (2), srvdefender01.offsec.lan (2), win10-02.offsec.lan (1)
high: MSEDGEWIN10 (124), IEWIN7 (70), fs03vuln.offsec.lan (30), FS03.offsec.lan (29), IE10Win7 (24)
medium: MSEDGEWIN10 (96), IEWIN7 (66), FS03.offsec.lan (26), fs03vuln.offsec.lan (25), srvdefender01.offsec.lan (19)
low: MSEDGEWIN10 (47), FS03.offsec.lan (23), IEWIN7 (22), fs03vuln.offsec.lan (18), fs01.offsec.lan (13)
informational: MSEDGEWIN10 (23), IEWIN7 (21), PC01.example.corp (19), fs01.offsec.lan (17), IE8Win7 (16)

╭──────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Top critical alerts:                                        Top high alerts:                                 │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ Sticky Key Like Backdoor Usage - Registry (8)               Metasploit SMB Authentication (3,562)            │
│ CobaltStrike Service Installations - System (6)             Malicious Svc Possibly Installed (271)           │
│ Active Directory Replication from Non Machine Account (6)   Susp Svc Installed (257)                         │
│ WannaCry Ransomware Activity (4)                            Suspicious Service Installation Script (250)     │
│ Defender Alert (Severe) (4)                                 PowerShell Scripts Installed as Services (250)   │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ Top medium alerts:                                          Top low alerts:                                  │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ Potentially Malicious PwSh (235)                            Logon Failure (Wrong Password) (3,564)           │
│ Proc Injection (104)                                        Susp CmdLine (Possible LOLBIN) (1,418)           │
│ Reg Key Value Set (Sysmon Alert) (103)                      Non Interactive PowerShell Process Spawned (325) │
│ Suspicious Remote Thread Target (93)                        Rare Service Installations (321)                 │
│ Remote Thread Creation Via PowerShell (93)                  Proc Access (156)                                │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ Top informational alerts:                                                                                    │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ Proc Exec (11,173)                                          Logon (Service) (Noisy) (434)                    │
│ NetShare File Access (2,564)                                NetShare Access (433)                            │
│ PwSh Scriptblock (789)                                      Svc Installed (331)                              │
│ PwSh Pipeline Exec (680)                                    Explicit Logon (304)                             │
│ DLL Loaded (Noisy) (550)                                    New Non-USB PnP Device (268)                     │
╰───────────────────────────────────────────────────────────╌──────────────────────────────────────────────────╯

Saved file: new.csv (33.6 MB)

Elapsed time: 00:00:09.592

Please report any issues with Hayabusa rules to: https://github.com/Yamato-Security/hayabusa-rules/issues
Please report any false positives with Sigma rules to: https://github.com/SigmaHQ/sigma/issues
Please submit new Sigma rules with pull requests to: https://github.com/SigmaHQ/sigma/pulls
```

**Comment by fukusuket** [comment]
### Test4
I have confirmed that there are only the following differences. (The differences below are from the rules that were merged into the Sigma repository today, so there is no problem.)
```
< Loaded rule: /rules/sigma/builtin/process_creation/proc_creation_win_mode_codepage_russian.yml
< Loaded rule: /rules/sigma/builtin/threat-hunting/process_creation/proc_creation_win_mode_codepage_change.yml
< Loaded rule: /rules/sigma/sysmon/deprecated/image_load_susp_uncommon_image_load.yml
< Loaded rule: /rules/sigma/sysmon/image_load/image_load_susp_unsigned_dll.yml
< Loaded rule: /rules/sigma/sysmon/process_creation/proc_creation_win_mode_codepage_russian.yml
< Loaded rule: /rules/sigma/sysmon/threat-hunting/process_creation/proc_creation_win_mode_codepage_change.yml
> Loaded rule: /rules/sigma/sysmon/image_load/image_load_susp_uncommon_image_load.yml
```

**Comment by fukusuket** [comment]
### Test5
rule parse error check passed.
https://github.com/Yamato-Security/hayabusa-rules/actions/runs/7612375592/job/20729855118?pr=581#step:5:4642

**Comment by fukusuket** [comment]
In the case below, a parse error occurred because I neglected to check after the last commit https://github.com/Yamato-Security/hayabusa-rules/pull/568/commits/f6bc46e4aff5efec3ab462b4f557ba31ab330f63 ... :(
https://github.com/Yamato-Security/hayabusa-rules/pull/568

This time, I have confirmed that there are no parse errors after the last commit.

I would appreciate it if you could review when you have time🙏

**Review by YamatoSecurity — APPROVED** [review]
@fukusuket LGTM! I checked that they now add comments and do not have parse errors.

**Pull request merged**
