### PR TITLE
feat: assign UUID for converted rules

### PR DESCRIPTION
**Pull request by fukusuket**
## What Changed
- Closed: #629 
- Closed: #632 
- Closed: #635 
- Related #627
- update exclude_rules.txt
### Environment
- OS: macOS Sonoma version 14.3.1
- Python 3.11.0

I would appreciate it if you could review when you have time🙏

### CODE REVIEW

**Comment by fukusuket** [comment]
I confirmed that derived is added as shown below.

original sigma rule: (e.g. [win_defender_antimalware_platform_expired.yml](https://github.com/SigmaHQ/sigma/blob/master/rules/windows/builtin/windefend/win_defender_antimalware_platform_expired.yml))
```yaml
title: Windows Defender Grace Period Expired
id: 360a1340-398a-46b6-8d06-99b905dc69d2
related:
    - id: fe34868f-6e0e-4882-81f6-c43aa8f15b62
      type: obsoletes
status: stable
description: |
    Detects the expiration of the grace period of Windows Defender. This means protection against viruses, spyware, and other potentially unwanted software is disabled.
references:
    - https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/troubleshoot-microsoft-defender-antivirus?view=o365-worldwide#event-id-5101
    - https://github.com/redcanaryco/atomic-red-team/blob/f339e7da7d05f6057fdfcdd3742bfcf365fee2a9/atomics/T1562.001/T1562.001.md
    - https://craigclouditpro.wordpress.com/2020/03/04/hunting-malicious-windows-defender-activity/
author: Ján Trenčanský, frack113
date: 2020/07/28
modified: 2023/11/22
tags:
    - attack.defense_evasion
    - attack.t1562.001
logsource:
    product: windows
    service: windefend
detection:
    selection:
        EventID: 5101 # The antimalware platform is expired.
    condition: selection
falsepositives:
    - Unknown
level: high
```

converted rule:
```yaml
title: Windows Defender Grace Period Expired
id: 5a62f5a9-71eb-a0e2-496d-e062350225df
related:
    - id: fe34868f-6e0e-4882-81f6-c43aa8f15b62
      type: obsoletes
    - id: 360a1340-398a-46b6-8d06-99b905dc69d2
      type: derived
status: stable
description: |
    Detects the expiration of the grace period of Windows Defender. This means protection against viruses, spyware, and other potentially unwanted software is disabled.
references:
    - https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/troubleshoot-microsoft-defender-antivirus?view=o365-worldwide#event-id-5101
    - https://github.com/redcanaryco/atomic-red-team/blob/f339e7da7d05f6057fdfcdd3742bfcf365fee2a9/atomics/T1562.001/T1562.001.md
    - https://craigclouditpro.wordpress.com/2020/03/04/hunting-malicious-windows-defender-activity/
author: Ján Trenčanský, frack113
date: 2020/07/28
modified: 2023/11/22
tags:
    - attack.defense_evasion
    - attack.t1562.001
logsource:
    product: windows
    service: windefend
detection:
    windefend:
        Channel: Microsoft-Windows-Windows Defender/Operational
    selection:
        EventID: 5101 # The antimalware platform is expired.
    condition: windefend and selection
falsepositives:
    - Unknown
level: high
ruletype: Sigma

```

**Comment by fukusuket** [comment]
### Test (rule files count)
I confirmed that there are no differences in the number of rules other than `6  near rule` below.
https://github.com/Yamato-Security/hayabusa-rules/issues/632#issue-2203856754
```
% find converted_sigma_rules_old -type f | wc -l
    4202
% find converted_sigma_rules_new -type f | wc -l
    4196
```

**Comment by fukusuket** [comment]
### Test(hayabusa-sample-evtx -D -n -u)
I confirmed that there are no differences in the results of the following command. (After updating exclude_rules.txt)
```
% ./hayabusa csv-timeline -d ../hayabusa-sample-evtx -r converted_sigma_rules_new -w -D -n -u -q -o new.csv
% ./hayabusa csv-timeline -d ../hayabusa-sample-evtx -r converted_sigma_rules_old -w -D -n -u  -q -o old.csv
% diff old.csv new.csv
%
```

**Comment by YamatoSecurity** [comment]
@fukusuket Thanks so much! LGTM!
I updated the English changelog. Could you update the Japanese one?
I confirmed the following improvements:
Sigma rules loaded: 4,176 -> 4,196 (+20)
Unique detections:  644 -> 737 (+93)

Just one question, only 20 new rules are added but unique detections has increased by 93. I am scanning against hayabusa-sample-evtx with deprecated and unsupported rules enabled. Do you know why there are so many more unique detections now?

**Comment by fukusuket** [comment]
@YamatoSecurity 
Thank you so much for checking :)
I think it's probably because haven't updated exclude_rule.txt, how about it? The UUID has changed, so I have updated it.
https://github.com/Yamato-Security/hayabusa-rules/blob/629-assign-uuid-for-converted-rules/config/exclude_rules.txt

In my environment, there was no difference between `Sigma rules loaded` and `Unique detections` before and after fix🤔

**Comment by fukusuket** [comment]
This is a different matter from the above, but I found another bug ...😅, so I fixed it as well.
- https://github.com/Yamato-Security/hayabusa-rules/issues/635

**Comment by YamatoSecurity** [comment]
> @YamatoSecurity Thank you so much for checking :) I think it's probably because haven't updated `exclude_rule.txt`, how about it? The UUID has changed, so I have updated it. https://github.com/Yamato-Security/hayabusa-rules/blob/629-assign-uuid-for-converted-rules/config/exclude_rules.txt
> 
> In my environment, there was no difference between `Sigma rules loaded` and `Unique detections` before and after fix🤔

Humm.. that is weird. This is the command I am running:
`./target/release/hayabusa csv-timeline -d ../hayabusa-sample-evtx -w -D -u -o test.csv -C -q -r ../hayabusa-rules -c ../hayabusa-rules/config`

In VS Code, I switched the `hayabusa-rules` branch to `rules/auto-sigma-update-1711252937`. Could you try scanning it using the rules in `rules/auto-sigma-update-1711252937` and let me know if there is any difference?

One question, if we are creating new IDs for `process_creation` rules, then does that mean we have to put both 2 IDs in `exclude_rules.txt`?

**Comment by fukusuket** [comment]
I see, there may be something wrong with my confirmation procedure... 😅 I'll check it!

**Comment by fukusuket** [comment]
@YamatoSecurity 
I checked `rules/auto-sigma-update-1711252937` branch!  In my environment, there was no difference.

But specified the **unmodified exclude-rule.txt** in the config as follows, it became **4,196 (+20)**, so I think that the `exclude-rule.txt` was probably not updated correctly?🤔 (It may be a VSCode checkout issue, so it may be better to separate the directories when checking?)
```
 % ./hayabusa csv-timeline -d ../hayabusa-sample-evtx -D -n -u -r converted_sigma_rules_new -w -o new.csv -c ./rules_bak/config -C -q
Start time: 2024/03/24 17:04

Total event log files: 585
Total file size: 137.2 MB

Loading detection rules. Please wait.


Deprecated rules: 205 (4.89%)
Experimental rules: 1,013 (24.14%)
Stable rules: 114 (2.72%)
Test rules: 2,817 (67.14%)
Unsupported rules: 47 (1.12%)

Sigma rules: 4,196
Total enabled detection rules: 4,196
```

**Comment by fukusuket** [comment]
>Unique detections: 644 -> 737 (+93)

Hayabusa's `Unique detections` are counted by UUID, so I think the reason is that rules that used to have the same UUID now have different UUIDs🤔(For example, `Security:4688` and `Sysmon:1` used to be the same UUID, but with this PR they will be different UUIDs.)

**Review by YamatoSecurity — APPROVED** [review]
> Hayabusa's `Unique detections` are counted by UUID, so I think the reason is that rules that used to have the same UUID now have different UUIDs🤔(For example, `Security:4688` and `Sysmon:1` used to be the same UUID, but with this PR they will be different UUIDs.)

Ok, that makes sense now! LGTM! I will merge this.

**Pull request merged**
